version: "3" # docker compose file version
services:
  myportfolio:
    container_name: myportfolio
    build: . # built from Dockerfile at current dir
    restart: always 
    env_file:
      - .env
    depends_on: # this service should start after mysql service
      - mysql

  mysql:
    container_name: mysql
    image: mariadb # lower resource usage replacement of mysql
    restart: always
    env_file:
      - .env
    volumes: # map volume to a directory
      - mydatabase:/var/lib/mysql

  nginx: # nginx service
    container_name: nginx
    image: jonasal/nginx-certbot # dockerhub image
    restart: always
    env_file:
      - .env # contains email for letsencrypt 
    ports:
      - 80:80 # port binding
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt # store cert files in host /etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d # map nginx config files from host into container
    depends_on:
      - myportfolio

volumes:
  mydatabase:
  nginx_secrets: