name: Run Tests # Workflow name
on: # triggers
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test: # this line is the job id, can't contain spaces
    runs-on: ubuntu-latest
    name: Run Tests # this is the job name, which is displayed in GitHub UI
    env:
      TESTING: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.6.8'

      - name: Setup Python Virtual Environment
        run: python -m venv python3-virtualenv
      
      - name: Install Dependencies
        run: python3-virtualenv/bin/pip install -r requirements.txt

      - name: Run Tests
        run: ./run_test.sh # the script activates the virtualenv so we don't have to run that here.